package ntnu.idatt2105.project.backend.model;

import io.swagger.v3.oas.annotations.media.Schema;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "users")
@Schema(description = "A registered user of the application")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "The id of the user, automatically and incrementally generated by database")
    private Long id;

    @Column(name = "name")
    @Schema(description = "The name of the user")
    private String name;

    @Column(name = "email")
    @Schema(description = "The email of the user")
    private String email;

    @Column(name = "password")
    @Schema(description = "The password of the user")
    private String password;

    @Column(name = "is_admin")
    @Schema(description = "The admin status of the user")
    private boolean isAdmin;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setAdmin(boolean admin) {
        isAdmin = admin;
    }
}