name: Build and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Test Frontend
        working-directory: ./vue-frontend
        run: |
          docker build -t my-frontend-image -f Dockerfile-test .
          docker run my-frontend-image

      - name: Build and Test Backend
        working-directory: ./backend
        run: |
          docker build -t my-backend-image -f Dockerfile-test .
          docker run my-backend-image mvn test